---
- name: old packages are removed
  become: true
  package:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: required packages are installed
  become: true
  package:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: docker gpg key is added
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ansible_lsb.id | lower}}/gpg"
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: docker repositories are added
  become: true
  apt_repository:
    filename: docker
    update_cache: true
    repo: 
      deb [arch={{ ( ansible_kernel | split('-') )[-1] }}
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/{{ ansible_lsb.id | lower }}
      {{ ansible_lsb.codename }} stable

- name: docker is installed
  become: true
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: docker is enabled
  become: true
  systemd:
    name: docker
    enabled: true
    state: started
...
