---
- name: old packages are removed
  become: true
  package:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: required packages are installed
  become: true
  package:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

# TODO : url: https://download.docker.com/linux/debian/gpg
- name: docker gpg key is added
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

# TODO : can we get this from ansible state
- name: retrive debian release
  command: lsb_release -cs
  register: release_name
  check_mode: false

# TODO : can we get this from ansible state
- name: retrive node's architecture
  command: dpkg --print-architecture
  register: arch_name
  check_mode: false

# TODO : adapt for https://download.docker.com/linux/debian
# TODO : make the repo string multiline

- name: docker repositories are added
  become: true
  apt_repository:
    filename: docker
    update_cache: true
    repo: "deb [arch={{ arch_name.stdout_lines[0] }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ release_name.stdout_lines[0] }} stable"

- name: docker is installed
  become: true
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: docker is enabled
  become: true
  systemd:
    name: docker
    enabled: true
    state: started
...
